spring.application.name=saber_aicha_4cce10

# Base de données
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# Serveur web (le port 8080 était déjà occupé)
server.port=8081
logging.level.org.hibernate.SQL=DEBUG
logging.level.tn.esprit.saber_aicha_4cce10=INFO